config/routes.rb
Rails.application.routes.draw do

  root to: "scripts#home"

  devise_for :users

  resources :users
  resources :scripts do
    resources :lines
    resources :authorships
  end
  

  

end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
	belongs_to :script
	belongs_to :user
end

app/models/line.rb
class Line < ActiveRecord::Base
	belongs_to :script
	belongs_to :user

	def fountain_type
		if /^(INT|EXT|EST|(I|INT)\\.?\\\/(E|EXT)\\.?)[\\.\\-\\s][^\\n]+$/.match(self.content)
			return "scene_heading"
		elsif /[^a-z]*(TO|IN):$/.match(self.content)
			return "transition"
		elsif /^[^a-z]+(\\(cont'd\\))?$/.match(self.content)
			return "character"
		end
		# we now have to do a query

		if self.position == 0
			return "scene_heading"
		end
		
		last_line_type = Line.find(self.position).content_type

		if last_line_type == "character" || last_line_type == "paranthetical"
			# last line character?
			if /[(].*[)]$/.match(self.content)
				return "paranthetical"
			else
				return "dialogue"
			end
		elsif /^$/.match(self.content) 
			return "blank_line"
		else
			return "action"
		end
	end

	def get_user_line_color
		@authorship = Authorship.where("script_id = ? AND user_id = ?", self.script_id, self.user_id).first!
		return @authorship.color
	end

	def parents_parent
		parent = Line.find(self.position)
		return parent.position
	end

end

app/models/script.rb
class Script < ActiveRecord::Base

	has_many :authorships
	has_many :users, through: :authorships
	has_many :lines, dependent: :destroy
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :authorships
	has_many :scripts, through: :authorships
	has_many :lines

	def calculate_lines_length(script)
		relevant_lines = Line.where("script_id = ? AND user_id = ?", script.id, self.id)
		total_length = 0
		relevant_lines.each do |line|
			words = line.content.split(' ')
			total_length += words.length
		end
		return total_length
	end

	def calculate_script_contribution(script)
		total_script_words = 0
		script.users.each do |writer|
			total_script_words += writer.calculate_lines_length(script)
		end
		given_user_words = self.calculate_lines_length(script)
		result = ((given_user_words.to_f / total_script_words.to_f) * 10000.0).round / 100.0
		return result
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authorships_controller.rb
class AuthorshipsController < ApplicationController

	def create
		@user = User.find_by(email: params[:email])
		@script = Script.find(params[:script_id])
		authorship = Authorship.new(script: @script, user: @user, color: "lightgreen")
		if authorship.save! 
			redirect_to edit_script_path(@script)
		end
	end

	def update
		@authorship = Authorship.find(params[:id])
		@authorship.color = params[:color]
		if @authorship.save
				redirect_to edit_script_path(@authorship.script)
		end
	end

	def destroy
	end

	private
	def authorship_params
		params.require(:authorship).permit(:email, :script_id, :color)
	end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

	respond_to :json

	def index
		@script = Script.find(params[:script_id])
		@lines = @script.lines.sort_by &:position
		respond_with @lines
	end

	def show
		@script = Script.find(params[:script_id])
		@lines = @script.lines.find(params[:id])
	end

	def new
		@script = Script.find(params[:script_id])
	end

	def create
		@user = current_user
		@script = Script.find(params[:script_id])
		@line = Line.new(line_params)
		@line.user = @user
		@line.script = @script

		@line.user_color = @line.get_user_line_color
		@line.content_type = @line.fountain_type

		if @line.save!
			respond_to do |format|
				format.json {render :show}
			end
		end
	end

	def update
		@user = current_user
		@line = Line.find(params[:id])
		@line.user = current_user
		@line.save
		@line.user_color = @line.get_user_line_color

		@line.content_type = @line.fountain_type
		@line.save
		if @line.update(line_params)
			respond_with @line
		end
	end

	def destroy
		@script = Script.find(params[:script_id])
	end

	private
	def line_params
	params.require(:line).permit(:content, :id, :position)
	end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController

	before_action :ensure_authorized_writer, only: [:show, :destroy]

	def home
		if user_signed_in?
			@user = current_user
			redirect_to @user
		else
			redirect_to new_user_session_path
		end
	end

	def show
		@script = Script.find(params[:id])
		@authorships = Authorship.where("script_id = ?", @script.id)
		@writers = @script.users
		render layout: "script_show"
	end

	def create
		@user = current_user
		@script = Script.new(script_params)
		@script.save!
		authorship = Authorship.new(user_id: @user.id, script_id: @script.id, color: "lightpink")
		authorship.save!
		redirect_to @script
	end

	def edit
		@script = Script.find(params[:id])
		@authorships = Authorship.where("script_id = ?", @script.id)
	end

	def update
		@script = Script.find(params[:id])
		@script.update(script_params)
			redirect_to @script
	end

	def destroy
		@script = Script.find(params[:id])
		@user = current_user
		if @script.destroy!
			redirect_to @user
		end
	end

	private
	def script_params
		params.require(:script).permit(:title)
	end

	def ensure_authorized_writer
		@script = Script.find(params[:id])
		if !@script.users.include?(current_user)
			redirect_to root_path
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@scripts = @user.scripts
		@script = Script.new
	end

	def new
	end

	def create
	end

	def edit
	end

	def update
	end

	def destroy
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<meta charset="utf-8">
	<title>AnyDraft</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

</head>
<body>

	<div class="container">

	<h1 class="logo-link">
		<a href="/"><span class="lightpink-logo">A</span><span class="lightgreen-logo">n</span><span class="lightcyan-logo">y</span><span class="underline-logo">Draft</span></a>
	</h1>

	<div class="user-auth-links">
		<% if current_user %>
			<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
		<% end %>
	</div>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>
	
	</div> <!-- end container -->
</body>
</html>

app/views/layouts/script_show.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<meta charset="utf-8">
	<title>AnyDraft</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'scriptApp', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



  <!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

</head>
<body>

	<div class="container">

	<h1 class="logo-link">
		<a href="/"><span class="lightpink-logo">A</span><span class="lightgreen-logo">n</span><span class="lightcyan-logo">y</span><span class="underline-logo">Draft</span></a>
	</h1>

	<div class="user-auth-links">
		<% if current_user %>
			<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
		<% end %>
	</div>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>
	
	</div> <!-- end container -->
</body>
</html>

app/views/scripts/edit.html.erb
<div class="five columns">
	<h2>Title</h2>
	<h3 class="script-title"><%= link_to(@script.title, @script) %></h3>
	<%= form_for @script do |f| %>
		<%= f.text_field :title %>
		<%= f.submit :Update %>
	<% end %>

	<h2>Remove Script</h2>
	<%= form_tag(script_path, method: "delete") do %>
		<%= submit_tag("Permanently Delete Script")%>
	<% end %>
</div>


<div class="five columns">
	<h2>Authors</h2>
	<ul>
		<% @script.users.each do |user| %>
			<li><%= link_to(user.email, user)%> (<%= user.calculate_script_contribution(@script)%>%)</li>
		<% end %>
	</ul>

	<%= form_tag("/scripts/#{@script.id}/authorships", method: "post") do %>
		<%= label_tag(:email, "Add a writer by email address:")%>
		<%= text_field_tag :email %>
		<%= submit_tag("Add Writer")%>
	<% end %>
</div>

<div class="five columns">
	<h2>Colors</h2>
	<% @authorships.each do |authorship| %>

	<%= authorship.user.email %>
		<%= form_tag("/scripts/#{authorship.script_id}/authorships/#{authorship.id}", method: "put") do %>
			<%= label_tag(:color, "Change Text Color")%>
			<%= select_tag(:color, options_for_select([["Pink", "lightpink"], ["Green", "lightgreen"]])) %>
			<%= submit_tag("Set Color")%>
		<% end %>
	<% end %>

</div>

app/views/scripts/home.html.erb
<div class="sixteen columns home-page-about">
	<h3><a href="/users/sign_up">Sign Up Now</a></h3>
</div>

app/views/scripts/show.html.erb
<div class="sixteen columns">
	<h2 class="script-title"><%= link_to(@script.title, edit_script_path(@script)) %></h2>
	<div class="writers">
		<p> Written By:
		<% @authorships.each do |writer| %>
			<span class="<%= writer.color %>"><%= link_to(writer.user.email, writer.user) %></span>, 
		<% end %></p>
	</div>
</div>


<div class="six columns">
	<h2>Fountain Editor</h2>
	<div class="editor">
	</div>
</div>

<div class="nine columns">
	<h2>Preview</h2>
	<div class="preview">
	</div>
</div>

<script type="text/template" id="line-input-template">
	<input type="text" class="line-content" value="<%%= content %>">
</script>

<script type="text/template" id="line-preview-template">
	<span class="<%%=user_color%>"><%%= content %></span>
</script>

app/views/scripts/show.js.erb
$(document).ready(function(){
	var app = new AppRouter();
	app.start();
});

app/views/users/index.html.erb
<ul>
	<% @users.each do |user| %>
	<li><%= link_to(user.email, user)%></li>
	<% end %>
</ul>

app/views/users/show.html.erb
<div class="sixteen columns">
	<p><%= @user.email %></p>
	<p>Date Joined: <%=  @user.created_at %></p>

	<h2>My Scripts</h2>
	<ul>
		<% @scripts.each do |script| %>
			<li><%= link_to(script.title, script) %></li>
		<% end %>
	</ul>

	<% if @user == current_user %>
		<h2>New Script</h2>
		<%= form_for @script do |f| %>
			<%= f.label "Title:" %>
			<%= f.text_field :title %>
			<%= f.submit :create %>
		<% end %>
	<% end %>
</div>